### ISSUE TITLE
A bug + suggestions

### ISSUE THREAD

**Issue by Puffiefishie** [Dekunutter/CherryBlossomGrotto#27]
When breaking the leaves, they turn green rather than staying pink. 

Also; would love to see compatibility with waving blocks (BSL shaders waving leaves) and motschen's better leaves!

**Comment by Dekunutter** [comment]
Hi, thanks for the bug report, I'll look into it.
Just to help me track down the issue, is it that the particle efffects are green instead of pink when harvesting the cherry blossom leaves block, or something to do with the entire block altering colour (which is not something I've seen happen before so maybe a compatibility issue with a shader pack).

**Comment by Puffiefishie** [comment]
It's the particle effect

**Comment by Dekunutter** [comment]
Just looping back to close this issue out at resolved. I tested the most recent versions of the mod after fixing some unrelated issues and saw no problems with the particle effects on any blocks anymore.

I also added support for Motschen's Better Leaves. To set that up you need to add some new files to the resourcepack. Instructions and content can be found here: https://github.com/Dekunutter/cherryblossomgrotto-betterleaves

No luck with getting the mod compatible with BSL waving leaves yet but hoping to look into this in the future.
