### ISSUE TITLE
Crafting Problem

### ISSUE THREAD

**Issue by popika98** [Dekunutter/CherryBlossomGrotto#28]
Hey, so I can't craft anything from this mode, I can't even make logs or anything with this.

**Comment by Dekunutter** [comment]
Hey, thanks for reporting the issue! Could you provide a little more information please? What version of the mod are you using?

**Comment by popika98** [comment]
I'm using the version 0.5.8
And sadly, anything I'm trying to craft from the mod, won't work(Katana, Lamp, Enhance Katana, Log to plnaks), I put them in the crafting table and nothing appears, if i'm on creative, yeah the items are there but sadly, I can't craft any of them
I've tried restarting the mod but nothing.
![image_2022-11-22_215007746](https://user-images.githubusercontent.com/118844252/203407993-ea80045a-39c7-46ad-b6c7-3d4bbe11c727.png)

**Comment by Dekunutter** [comment]
Ok perfect thank you for the additional info. That sucks cause I thought this worked fine last I tried it. I am traveling this week but next week once I'm back home I'll look into getting this fixed.

**Comment by popika98** [comment]
Thank you man
Just wanted to say this is an amazing mod and thank you for all the efforts

**Comment by Dekunutter** [comment]
I just released version 0.5.11 on CurseForge and Modrinth. This should fix the issues you encountered with crafting. Turns out two recipes were broken, crafting logs into planks and katana folding.

Thanks again for reporting the issue to me! I will close out this thread now. If you continue to see this problem in the new version, or encounter different issues, feel free to create a new thread and I'll address them there
